"""Sampling of the LLPR ensemble weights from the fitted covariance. Called
from Python (the LLPR trainer and tests), never from the TorchScript forward
path."""

import torch
from metatomic.torch import ModelCapabilities, ModelOutput

from metatrain.utils.last_layer import (
    assemble_block_weights,
    resolve_last_layer_slices,
)

from .model import (
    LLPRUncertaintyModel,
    get_ensemble_name,
    get_uncertainty_name,
)


def generate_ensemble(model: LLPRUncertaintyModel) -> None:
    """Generate an ensemble of weights for the model.

    The ensemble is generated by sampling from a multivariate normal
    distribution with mean given by the input weights and covariance given
    by the inverse covariance matrix.

    :param model: the LLPR model to generate ensemble weights for.
    """
    device = next(iter(model.buffers())).device
    dtype = next(iter(model.buffers())).dtype

    state_dict = model.model.state_dict()

    for name, num_members in model.ensemble_weight_sizes.items():
        uncertainty_name = get_uncertainty_name(name)

        # each target block has its own last layer, so it is sampled separately;
        # the covariance belongs to the feature block the last layer reads (the
        # single shared one for invariant features, the block's own for
        # equivariant ones), and the multiplier is the block's own
        resolved = resolve_last_layer_slices(model.model, name)
        for block_key in model.ensemble_block_keys[name]:
            block_index = model.target_block_keys[name].index(block_key)
            feature_index = model.block_feature_index[name][block_index]
            cur_cholesky = model._get_cholesky(
                uncertainty_name,
                model.feature_keys[name][feature_index],
            )
            # effective weight matrix of this block's readout, assembled from
            # the slices the architecture declares; shape (n_prop, n_features)
            weights = assemble_block_weights(state_dict, resolved[block_key])
            cur_multiplier = model._get_multiplier(uncertainty_name, block_key)

            # fold in the wrapped model's scales (see `_block_scales`); the
            # re-centering in `forward` pins the ensemble mean regardless
            block_scales = model._get_scales(uncertainty_name, block_key)

            ensemble_weights = []

            for ii in range(weights.shape[0]):
                z = torch.randn(
                    (weights.shape[1], num_members),
                    device=device,
                    dtype=dtype,
                )
                # using the Cholesky decomposition to sample from the multivariate
                # normal distribution
                ensemble_displacements = (
                    torch.linalg.solve_triangular(
                        cur_cholesky.T,
                        z,
                        upper=True,
                    )
                    * cur_multiplier.item()
                )
                cur_ensemble_weights = weights[ii].unsqueeze(1) + ensemble_displacements
                # rows run over the components first and the properties last,
                # so the property index is `ii % n_properties`
                cur_ensemble_weights = (
                    cur_ensemble_weights
                    * block_scales[ii % block_scales.shape[0]].item()
                )
                ensemble_weights.append(cur_ensemble_weights)

            stacked_weights = torch.stack(
                ensemble_weights,
                axis=-1,
            )  # shape: (ll_feat, n_ens, n_subtarget)
            stacked_weights = stacked_weights.reshape(
                stacked_weights.shape[0],
                -1,
            )  # shape: (ll_feat, n_ens * n_subtarget)
            # assign the generated weights
            with torch.no_grad():
                model.llpr_ensemble_layers[f"{name}::{block_key}"].weight.copy_(
                    stacked_weights.T
                )

    # add the ensembles to the capabilities
    old_outputs = model.capabilities.outputs
    new_outputs = {}
    for name in model.ensemble_weight_sizes.keys():
        ensemble_name = get_ensemble_name(name)
        new_outputs[ensemble_name] = ModelOutput(
            unit=old_outputs[name].unit,
            sample_kind=old_outputs[name].sample_kind,
            explicit_gradients=model._ensemble_explicit_gradients(name),
            description=f"ensemble of '{name}'",
        )
    model.capabilities = ModelCapabilities(
        outputs={**old_outputs, **new_outputs},
        atomic_types=model.capabilities.atomic_types,
        interaction_range=model.capabilities.interaction_range,
        length_unit=model.capabilities.length_unit,
        supported_devices=model.capabilities.supported_devices,
        dtype=model.capabilities.dtype,
    )
